export const SEO_KEYWORDS_EN = [
  "free online notepad",
  "online notepad",
  "online notepad free",
  "online notepad realtime",
  "realtime online notepad",
  "realtime collaborative notepad",
  "collaborative online editor",
  "collaborative text editor",
  "collaborative notes app",
  "shared online notes",
  "shared notes platform",
  "shared text editor",
  "live collaborative editor",
  "live notes collaboration",
  "open source online notepad",
  "open source collaborative editor",
  "open source notes platform",
  "browser based text editor",
  "browser notepad",
  "online text editor",
  "online memo pad",
  "temporary online notes",
  "quick online notes",
  "instant note sharing",
  "cloud notepad",
  "cloud notes editor",
  "simple online notepad",
  "minimal online editor",
  "online scratchpad",
  "web notepad",
  "web based notepad",
  "free collaborative editor",
  "free shared notes",
  "free realtime editor",
  "free online notes",
  "realtime shared notes",
  "realtime document collaboration",
  "online collaborative workspace",
  "team collaboration notes",
  "meeting notes online",
  "online brainstorming notes",
  "shared project notes",
  "remote team notes",
  "agile meeting notes",
  "daily standup notes",
  "live coding notes",
  "coding notes online",
  "markdown collaborative editor",
  "markdown online editor",
  "rich text collaborative editor",
  "rich text online editor",
  "tiptap collaborative editor",
  "yjs collaborative editor",
  "crdt collaborative editor",
  "self hosted notepad",
  "self hosted collaborative editor",
  "private online notes",
  "secure online notepad",
  "pin protected notes",
  "locked collaborative notes",
  "temporary text sharing",
  "anonymous online notes",
  "no login notepad",
  "no signup notes",
  "instant collaborative notes",
  "share notes with link",
  "url based notepad",
  "dynamic url notes",
  "notepad with share link",
  "shared memo pad",
  "simple collaborative notes",
  "online notes for teams",
  "browser based collaborative notes",
  "collaborative writing platform",
  "realtime document editor",
  "online collaborative document",
  "free collaborative workspace",
  "free online collaboration tool",
  "online team editor",
  "collaborative workspace online",
  "minimal productivity tool",
  "lightweight online editor",
  "fast online notes",
  "instant online editor",
  "open source productivity app",
  "realtime productivity tool",
  "web collaborative editor",
  "web based shared notes",
  "online editor without login",
  "temporary collaborative editor",
  "online pad realtime",
  "shared pad online",
  "live text synchronization",
  "realtime sync editor",
  "collaborative knowledge sharing",
  "team note sharing",
  "free remote collaboration tool",
  "notepad alternative",
  "google docs alternative",
  "etherpad alternative",
  "minimal notes platform",
  "realtime notes platform",
  "simple team collaboration tool",
  "fast realtime notepad",
  "free shared document editor",
  "online collaboration software",
  "lightweight collaborative app",
  "browser based productivity tool",
  "cross platform notes editor",
  "responsive online editor",
  "docker collaborative editor",
  "nextjs collaborative editor",
  "opensource realtime collaboration",
  "markdown notes collaboration",
  "online markdown notes",
  "export txt markdown notes",
  "txt md export editor",
  "realtime markdown collaboration",
  "online note taking app",
  "free browser editor",
  "realtime browser editor",
  "collaborative browser editor",
  "shared browser notes",
  "unlimited online notes",
  "public collaborative notes",
  "private collaborative workspace",
  "encrypted notes collaboration",
  "temporary workspace online",
  "team realtime notes",
  "online collaborative whitepaper notes",
  "remote collaboration editor",
  "distributed realtime editing",
  "multiplayer text editor",
  "realtime synced notes",
  "online notepad without install",
  "websocket collaborative editor",
  "postgres collaborative notes",
  "prisma collaborative editor",
  "tailwind online editor",
  "react collaborative editor",
  "typescript collaborative app",
  "dockerized notepad platform",
  "modern online notepad",
  "SEO optimized online notepad",
  "AI friendly notes platform"
] as const;

export const SEO_KEYWORDS_ID = [
  "notepad online gratis",
  "catatan online realtime",
  "notepad kolaboratif realtime",
  "editor teks kolaboratif",
  "aplikasi catatan kolaboratif",
  "catatan online bersama",
  "platform catatan bersama",
  "editor teks bersama",
  "kolaborasi catatan live",
  "notepad online open source",
  "editor kolaboratif open source",
  "platform catatan open source",
  "editor teks berbasis browser",
  "notepad browser",
  "editor teks online",
  "memo online",
  "catatan online sementara",
  "catatan online cepat",
  "berbagi catatan instan",
  "notepad cloud",
  "editor catatan cloud",
  "notepad online sederhana",
  "editor online minimal",
  "notepad web",
  "editor kolaboratif gratis",
  "catatan bersama gratis",
  "editor realtime gratis",
  "catatan tim online",
  "catatan rapat online",
  "catatan brainstorming online",
  "catatan proyek bersama",
  "catatan tim remote",
  "catatan daily standup",
  "catatan coding online",
  "editor markdown kolaboratif",
  "editor rich text kolaboratif",
  "editor tiptap kolaboratif",
  "editor yjs kolaboratif",
  "editor crdt kolaboratif",
  "notepad self hosted",
  "catatan online privat",
  "notepad online aman",
  "catatan dengan pin",
  "catatan kolaboratif terkunci",
  "catatan online anonim",
  "notepad tanpa login",
  "catatan tanpa daftar",
  "berbagi catatan lewat link",
  "notepad berbasis url",
  "catatan url dinamis",
  "notepad dengan share link",
  "catatan online untuk tim",
  "platform menulis kolaboratif",
  "editor dokumen realtime",
  "dokumen kolaboratif online",
  "workspace kolaborasi gratis",
  "alat kolaborasi online gratis",
  "editor tim online",
  "workspace kolaboratif online",
  "alat produktivitas minimal",
  "editor online ringan",
  "catatan online cepat",
  "editor online instan",
  "aplikasi produktivitas open source",
  "alat produktivitas realtime",
  "editor kolaboratif web",
  "catatan bersama berbasis web",
  "editor online tanpa login",
  "editor kolaboratif sementara",
  "sinkronisasi teks live",
  "editor sinkron realtime",
  "berbagi pengetahuan kolaboratif",
  "berbagi catatan tim",
  "alat kolaborasi remote gratis",
  "alternatif notepad",
  "alternatif google docs",
  "alternatif etherpad",
  "platform catatan minimal",
  "platform catatan realtime",
  "alat kolaborasi tim sederhana",
  "notepad realtime cepat",
  "editor dokumen bersama gratis",
  "software kolaborasi online",
  "aplikasi kolaboratif ringan",
  "alat produktivitas berbasis browser",
  "editor catatan lintas platform",
  "editor online responsif",
  "editor kolaboratif docker",
  "editor kolaboratif nextjs",
  "kolaborasi realtime open source",
  "kolaborasi catatan markdown",
  "catatan markdown online",
  "export catatan txt markdown",
  "kolaborasi markdown realtime",
  "aplikasi pencatatan online",
  "editor browser gratis",
  "editor browser realtime",
  "editor browser kolaboratif",
  "catatan browser bersama",
  "catatan online tanpa batas",
  "catatan kolaboratif publik",
  "workspace kolaboratif privat",
  "kolaborasi catatan terenkripsi",
  "workspace online sementara",
  "catatan realtime tim",
  "editor kolaborasi remote",
  "editing realtime terdistribusi",
  "editor teks multiplayer",
  "catatan sinkron realtime",
  "notepad online tanpa install",
  "editor kolaboratif websocket",
  "catatan kolaboratif postgres",
  "editor kolaboratif prisma",
  "editor online tailwind",
  "editor kolaboratif react",
  "aplikasi kolaboratif typescript",
  "platform notepad dockerized",
  "notepad online modern",
  "notepad online SEO optimized",
  "platform catatan ramah AI"
] as const;

export const SEO_KEYWORDS_COMBINED = [...SEO_KEYWORDS_EN, ...SEO_KEYWORDS_ID];
